#pragma once
#include "../src/Network.h"
#include "../src/exec.h"
#include "../src/layers.h"
#include "../src/permute.h"
#include "../src/symmetry.h"
#include "../src/tikz.h"
#include "../src/format.h"
#include "../src/parse.h"